import Header from "@/components/Header";
import PromptInput from "@/components/PromptInput";
import "./globals.css";

export const metadata = {
  title: "Dall-E 2.0 ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header   */}
        <Header />

        {/* Prompt Input */}
        <PromptInput />

        {children}
      </body>
    </html>
  );
}
